### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by babakness** [trusktr/infamous#118]
SSL certificate at infamous.io has expired.

**Comment by trusktr** [comment]
Thanks for pointing it out Babak! I'll get to that by this weekend.

**Comment by trusktr** [comment]
I also recently converted from Babel to Buble to make the library code leaner and faster, and will start on the documentation pages for the site next. Finally there will be docs! :D

**Comment by trusktr** [comment]
Alright, fixed! :}
