### ISSUE TITLE
Add all-contributors

### ISSUE THREAD

**Issue by trusktr** [trusktr/infamous#120]
https://github.com/kentcdodds/all-contributors

@corruptedzulu Would you be interested in doing this, to help you get more familiar with the code base?

**Comment by trusktr** [comment]
Approved the PR. Future work: automate generation of the contributor list, https://github.com/trusktr/infamous/issues/127

**Comment by corruptedzulu** [comment]
Pull request for this issue has been merged. Marking closed.
