### ISSUE TITLE
Make an Observable or EventEmitter class/pattern.

### ISSUE THREAD

**Issue by trusktr** [trusktr/infamous#54]
Use the pattern to watch for changes on properties of for example the XYZValues class, so that we don't have to hard code the functionality, and can re-use it. Perhaps make it a mixin.

I found the need for this when I ran into the problem in #56. I'll finish this issue first, then solve that one.

**Comment by trusktr** [comment]
Once we make this, organize the _needsToBeRendered method (where it is defined and how it is called  with events).

**Comment by steveblue** [comment]
Why not just use rxjs?

**Comment by trusktr** [comment]
@steveblue Hi Steve, nice to hear from you! I'll check that out. From a quick glance it seems a bit heavy weight compared to what I'm imagining, but maybe I can import only what I need if the classes are simple enough.

**Comment by newswim** [comment]
Just want to give a modest +1 for integrating RxJS (5.0).. lots features for streaming and pub/style event handling and it's intended to follow Observer spec very closely.

**Comment by steveblue** [comment]
@trusktr You can just import `rxjs/Observable` and every method you want to use a la carte

**Comment by trusktr** [comment]
@steveblue I just gave it a deeper look, and it seems the observable class is using an async scheduler class. It might be too heavy. Instead of a tool for observing arbitrary objects, the pattern I'm imagining here makes observation explicit whereby the things to be observed will need to extend from (or have mixed in) the observable traits, and same with observers, and it will likely all be synchronous at first (though possibly with optional async behavior later).

**Comment by trusktr** [comment]
Still thinking about it though. I want it to be as light-weight as possible with the minimal features needed.

**Comment by trusktr** [comment]
@newswim Read your message late. I think I'm gonna make a really simple implementation, that will be used for the private parts of the API, but it will still be possible as an end-app-developer to use rxjs to observe (for example) Node and Scene instances in order to react to changes in position, rotation, etc.

I'm still thinking about it, but rxjs may be too heavy for what I need.

**Comment by trusktr** [comment]
Basic Observable class made in a8f1d78132462459cf08aba01cff71fa8b130b68

**Comment by trusktr** [comment]
By the way, the pattern I'm using with `ObservableMixin` and other classes is partly based on http://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/.
